# Generated by Django 4.2.11 on 2024-04-27 06:22

from django.db import migrations, models
import django.db.models.deletion
import jambo.apps.customers.models


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Business category',
                'verbose_name_plural': 'Business categories',
            },
        ),
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('sub_county', models.CharField(db_index=True, max_length=150)),
                ('ward', models.CharField(db_index=True, max_length=150)),
                ('building_name', models.CharField(db_index=True, max_length=200)),
                ('floor', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Business location',
                'verbose_name_plural': 'Business locations',
                'unique_together': {('county', 'sub_county', 'ward', 'building_name', 'floor')},
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Customer contact',
                'verbose_name_plural': 'Customer contacts',
                'unique_together': {('phone', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('registration_date',
                 models.DateField(db_index=True, validators=[jambo.apps.customers.models.past_date_validator])),
                ('categories', models.ManyToManyField(related_name='categories', to='customers.businesscategory')),
                ('location',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.businesslocation')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('date_of_birth',
                 models.DateField(db_index=True, validators=[jambo.apps.customers.models.past_date_validator])),
                ('contact',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.customercontact')),
                ('businesses', models.ManyToManyField(to='customers.business')),
                ('nationality', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
