# Generated by Django 4.2.11 on 2024-04-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='businesses',
            field=models.ManyToManyField(to='customers.business'),
        ),
    ]
