# Generated by Django 4.2.11 on 2024-04-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_businesses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='businesscategory',
            options={'verbose_name': 'Business category', 'verbose_name_plural': 'Business categories'},
        ),
        migrations.AlterModelOptions(
            name='businesslocation',
            options={'verbose_name': 'Business location', 'verbose_name_plural': 'Business locations'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customercontact',
            options={'verbose_name': 'Customer contact', 'verbose_name_plural': 'Customer contacts'},
        ),
        migrations.AlterUniqueTogether(
            name='businesslocation',
            unique_together={('county', 'sub_county', 'ward', 'building_name', 'floor')},
        ),
    ]
