# Generated by Django 4.2.11 on 2024-04-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_business_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customercontact',
            unique_together={('phone', 'email')},
        ),
    ]
